### ISSUE TITLE
SQL Server CE dosen't recognize SCOPE_IDENTITY()

### ISSUE THREAD

**Issue by cnwilkin** [FransBouma/Massive#210]
While working through your Read-World ASP.NET MVC3 course on [Pluralsight](http://pluralsight.com/training/Courses/TableOfContents/real-world-aspdotnet-mvc3) and ran across this error. The exact error message is a follows 

```
The function is not recognized by SQL Server Compact. [ Name of function = SCOPE_IDENTITY,Data type (if known) =  ]
```

Changing the code from

```
cmd.CommandText = "SELECT SCOPE_IDENTITY() as newID";
```

to

```
 cmd.CommandText = "SELECT @@IDENTITY as newID";
```

seems to fix the problem but I don't know if this breaks any other versions of SQL.  Should this be a pull request or should I just change it in my local copy?

**Comment by Nathan0710** [comment]
I have same problem but mine was CONCAT. It says

The function is not recognized by SQL Server Compact. [ Name of function = CONCAT,Data type (if known) = ].
