### ISSUE TITLE
Massive.Sqlite and Pageing

### ISSUE THREAD

**Issue by pierreSLA** [FransBouma/Massive#214]
I have found two bugs in the pageing method. One is condition specific; the where clause is added to the main statement without a space. 
The other bigger issue is with the dynamic field "Items". It can not be resolved. An C# 5.0 dynamic issue: "'Massive.SQLite.DynamicModel.Query(string, params object[])' is a 'method' but is used like a 'type'"

I must call the toList on the method call, but then i lose the post call, If items aren't really needed.

**Comment by FransBouma** [comment]
In the 'Refactoring' branch, I've now added the SQLite port, with tests. this will soon be v2.0. You can grab Massive.Shared.cs and Massive.Sqlite.cs to get sqlite working today.
