### ISSUE TITLE
Add async/await code

### ISSUE THREAD

**Issue by FransBouma** [FransBouma/Massive#228]
It's rather easy to add async/await methods to Massive, the only problem is that it will also make the code .NET 4.5+ automatically, which is a bit of a problem perhaps. I don't want to create yet another clone per DB for async/await so this also ties to the discussion in #223. 

At the moment async/await at the ADO.NET level has been implemented in sqlclient only anyway (Oracle ODP.NET doesn't support it yet and npgsql will support it in v3 but that's not released yet). 

We could add conditionals to the code for the users to add to their projects, so to wrap the code like:
```csharp
#if MASSIVE_NET45
// async code here
#endif
```
and then to get the async code, people have to add MASSIVE_NET45 to the compile directives of their project.

Any questions/remarks about this approach? Perhaps another approach is more handy?

**Comment by txdv** [comment]
Maybe we could use [partial classes](https://msdn.microsoft.com/en-us/library/wa80x488.aspx) and put everything 4.5 related in a separate file?

**Comment by FransBouma** [comment]
In the repo 'Refactoring' I've started using partial classes to split generic from db specific code, and it turned out that most code is generic and only a bit is db specific. Another partial class to the generic code might indeed help for the async code as well.

**Comment by FransBouma** [comment]
Implemented (In Refactoring branch). https://github.com/FransBouma/Massive/commit/aeb3fc33f75754958743fa7fbd98c932d2b6367a
