### ISSUE TITLE
Any plans to support transactions?

### ISSUE THREAD

**Issue by comfreakph** [FransBouma/Massive#234]
the current version doesn't support transactions, is there plan for add this to massive?

**Comment by FransBouma** [comment]
It does https://github.com/FransBouma/Massive/blob/master/Massive.cs#L274 but not directly. You want directly defined transactions (like you define: 'start a transaction', then do things (so the actions are all in the transaction), then 'commit transaction' ? ) besides the indirect transaction defined now?

**Comment by comfreakph** [comment]
yes direct defined transactions like in EF. 
ex:

db.create(model);
db.savechanges();

^_^

**Comment by aleblanc70** [comment]
Hello Frans,

The link in your previous post does not work :(

Yep transaction will be great. 
So in our code we could update many row and on exception ROLL BACK all.
Thanks!
André

**Comment by mikebeaton** [comment]
The links:
https://github.com/FransBouma/Massive/blob/v1.0/Massive.cs#L274
https://github.com/FransBouma/Massive/blob/v2.0/src/Massive.Shared.cs#L418
(A somewhat relevant issue, at least for 'roll-your-own' transaction support: #301)

**Comment by FransBouma** [comment]
Massive doesn't have the design to have a Unit of work and a separate transaction requires also a separate connection, which is shared among operations. Massive's design doesn't really support that. It does have internal transactions but no external transaction. If you want that, use a System.Transactions.TransactionScope.
