### ISSUE TITLE
Resultset as Datatable

### ISSUE THREAD

**Issue by wcervini** [FransBouma/Massive#238]
Can include Datatable an part of ObjectExtension 
public static DataTable ToDataTable(this IEnumerable<dynamic> items)
        {
            var data = items.ToArray();
            if (data.Count() == 0) return null;
            var dt = new DataTable();
            foreach (var key in ((IDictionary<string, object>)data[0]).Keys)
            {
                dt.Columns.Add(key);
            }
            foreach (var d in data)
            {
                dt.Rows.Add(((IDictionary<string, object>)d).Values.ToArray());
            }
            return dt;
        }

**Comment by FransBouma** [comment]
Could you fork the repo and add it to the Refactoring branch? thanks :) (btw, the column addition won't work that way, you need types too. )

**Comment by FransBouma** [comment]
Implemented #261
