### ISSUE TITLE
ID returning null after insert with auto-increment primary key

### ISSUE THREAD

**Issue by luisvsilva** [FransBouma/Massive#241]
After insert, ID property is set to null.

Changing:
this:
cmd.CommandText = "SELECT SCOPE_IDENTITY()";

to:
cmd.CommandText = "SELECT @@IDENTITY as newID";

in Insert method, fixed it.

Also why is ID hardcoded, shouldnt we be using the PrimaryKeyField property as per stated in the documentation?

I can submit a push request if needed.

Thanks

**Comment by FransBouma** [comment]
Could you try the version in the refactoring branch? I've been refactoring Massive in the past months (when I have time), fixed some bugs and made things better (and added tests!). 

About your fix: it suggests you have a trigger on the table, is that correct?

**Comment by luisvsilva** [comment]
I will try the version in the re-factoring branch and check back.

About the fix: No triggers.
