### ISSUE TITLE
Prototype Property Issue-MSSQL

### ISSUE THREAD

**Issue by arlewis2015** [FransBouma/Massive#245]
This project is amazing.Great Work to all on this.
A couple of questions around the expected use of the Prototype property.
It seems no matter which way I attempt to use this it always sends the request to the TryInvokeMember function ie as the dynamic use should.

I have tried the following ways and cannot seem to get it to work .

From the main documentation:
Employee is defined as follows:
  public class Employee : DynamicModel
    {
        //you don't have to specify the connection - Massive will use the first one it finds in your config
        public Employee() : base("CONNNAME", "Employee", "EmployeeId") { }
    }
 var table = new Employee();
 dynamic sampleResult = table.Prototype;

This hits the TryInvokeMember which errors out at:
throw new InvalidOperationException("Please use named arguments for this type of query - the column name, orderby, columns, etc");

I have also tried as true dynamic
 dynamic table = new Employee();
 dynamic sampleResult = table.Prototype;

I get the same result.

Can anyone provide me the intended way to invoke this property?

**Comment by FransBouma** [comment]
Does it also do this with the refactored version (in the refactoring branch) ?

**Comment by arlewis2015** [comment]
Yes,
The refactoring version for MSSQL is where this seems to be happening.As the refactoring version is the one that I am using.

**Comment by arlewis2015** [comment]
I just tested the master branch version Massive.cs and it seems to behave as expected(without issue) using the following code.

 var em = new Employee();
 dynamic d = em.Prototype;

**Comment by FransBouma** [comment]
Weird. I'll look into it. Won't be soon though, likely after the weekend.

**Comment by arlewis2015** [comment]
I think I have this nailed down.
It appears on the refactor branch only and the code in question is as follows:
From the original Massive.cs file it uses the dynamic for the column passed:

```
 /// <summary>
        /// Gets a default value for the column
        /// </summary>
        public dynamic DefaultValue(dynamic column) {
            dynamic result = null;
            string def = column.COLUMN_DEFAULT;
            if (String.IsNullOrEmpty(def)) {
                result = null;
            } else if (def == "getdate()" || def == "(getdate())") {
                result = DateTime.Now.ToShortDateString();
            } else if (def == "newid()") {
                result = Guid.NewGuid().ToString();
            } else {
                result = def.Replace("(", "").Replace(")", "");
            }
            return result;
        }
```

From the current refactor branch it passes an expected string and then does the conversion over:

```
/// <summary>
        /// Gets a default value for the column with the name specified as defined in the schema.
        /// </summary>
        /// <param name="columnName">Name of the column.</param>
        /// <returns></returns>
        public dynamic DefaultValue(string columnName)
        {
            var column = GetColumn(columnName);
            if(column == null)
            {
                return null;
            }
            return GetDefaultValue(column);
        }
```

 A solution to the problem would be in the following line on the refactor branch:
Line 1127 change from the current which I commented out and pass the expected string type to the method

```
 //dc.Add(this.GetColumnName(column), this.DefaultValue(column));
```

To

```
 dc.Add(column.COLUMN_NAME, this.DefaultValue(column.COLUMN_NAME));
```

This will resolve the issue

**Comment by FransBouma** [comment]
ah! 

It has to be checked whether it works with all DBs as this code is now shared among all DBs. (i.o.w. column.COLUMN_NAME isn't necessarily the right name, this has to be checked).

Good catch!

**Comment by arlewis2015** [comment]
Totally agree.

**Comment by FransBouma** [comment]
Issue seem to be on the `var schema=Schema` line in the Prototype property: schema results in an empty object, so the forloop obviously doesn't do anything. Looking into it.

**Comment by FransBouma** [comment]
I ran into a bug that's not related to this (schema in tablename=> Schema query fails). Will fix that one first.

**Comment by FransBouma** [comment]
Reproduced

**Comment by FransBouma** [comment]
Fixed
