### ISSUE TITLE
Massive.Tests - Unable to perform unit tests on Oracle project

### ISSUE THREAD

**Issue by AlphaGeek509** [FransBouma/Massive#249]
While attempting to review the information pertaining to the Oracle database, Oracle and PostgreSql unit test do not appear to be producing any output (via Test Explorer VS 2k13).  Sqlite and SqlServer function as designed.  Is the unit test information for these projects designed to be fully functional for testing, or as stated in the readMe, "Unit Tests. In v1.0 there were no tests but in v2.0 we properly implemented a series of tests to see whether things indeed work the way they do. They can also be used as an example how to get started."

**Comment by FransBouma** [comment]
The tests are designed to be run on a DB which matches the tests, which is for Oracle the SCOTT example schema (which on 12c has to be installed manually if I recall correctly) and for Postgresql the Northwind schema, which has to be created manually. I don't know what you mean with 'don't produce any output': the test fails, succeeds, or isn't run at all?

**Comment by AlphaGeek509** [comment]
Good statements and questions, let me clarify.

In my environment, I've changed Massive.Test.Oracle\App.config to properly read from my Oracle 11g database.  I've modified Dept.cs inside of Massive.Tests.Oracle\TableClasses to correctly read from MY department table.  During a very small experiment I was able to successfully connect to the database, build the model and query against it.  All of this was done by using your examples in the README/Code Please section.

So, to the best of my ability, if I'm able to connect to the database, extract a model and query data it would stand to reason that during a unit test (Massive.Tests.Oracle\ReadWriteTest.cs) I would be able to expect results during a Run All via Test Explorer.

Am I not doing something correctly since I'm not seeing any Assert validations from the ReadWriteTest.cs duing a rebuild of the solution?

Thanks for taking the time to address this issue that I'm having.  I've only just begun working with your micro ORM and I can already tell that it's going to work well in my Oracle enviroment.  Keep up the great work and I look forward to contributing to this project in the near future.

**Comment by AlphaGeek509** [comment]
This issue can be closed as it is a development machine problem.  I'm sorry for the inconvenience and thanks again for this project and your time.

**Comment by FransBouma** [comment]
Thanks Jeff. :) I had some 'tests not running' issue with vs.net yesterday as well. (different project) did you find out what the cause was? Perhaps it's the same issue on my machine. I use nunit adapter to discover tests in vs.net and run them in test explorer.

**Comment by AlphaGeek509** [comment]
I'm almost embarrassed to say, I neglected test as the x64 processor on the new development machines.  I forgot that was the machine I built and the ODP.NET connector I downloaded.  Thanks for the followup.
