### ISSUE TITLE
ODP.NET: Oracle LONG text data not fetched

### ISSUE THREAD

**Issue by FatPanther** [FransBouma/Massive#253]
Working with a legacy db & came across another ODP.NET "feature": OracleCommand property InitialLONGFetchSize is 0 by default, which, for columns of Oracle type LONG, causes no data to be fetched.  Setting it to -1 gets us all the data.

I realize that LONG is little used so this may be considered an edge case, but figured I'd mention it especially after looking at #252, which outlines a similar need to set a property on OracleCommand to work around such features :-)  Thanks!

**Comment by FransBouma** [comment]
Yeah LONG is solved the same way as named parameters :) We can add both with similar code using reflection.

**Comment by FransBouma** [comment]
Implemented in pull #256
