### ISSUE TITLE
.Save() not inserting PK field

### ISSUE THREAD

**Issue by AlphaGeek509** [FransBouma/Massive#257]
I've defined my model, I believe, correctly.

``` c#
public clsPRINT_REV_CTRLModel(bool includeSchema) 
: base(TestConstants.SAND7, includeSchema ? "LT_DB.PRINT_REV_CTRL" : "PRINT_REV_CTRL", "ID", string.Empty, includeSchema ? "LT_DB.PRINT_REV_CTRL_SEQ" : "PRINT_REV_CTRL_SEQ")
     {
          initialize();
     }
```

During recent a recent test of the .Save method I'm receiving an error where of ORA-01400: cannon insert NULL into PRINT_REV_CTRL.ID, where ID is my PK of the table.  **INSERT** works exactly as intended, and that's when I noticed it.  There is a great sequence call in Massive.Shared.cs on line 678 that plays an important role.

Any suggestions on which way I should go with this?

Perhaps, I'm going about .Save() wrong.  Perhaps .Save() was not designed to create a PK during the insert.  The comment on the .Save() method I can see could be read as such.

**Comment by FransBouma** [comment]
Best way to deal with this is to create a failing test in a fork, so I can look at it :)

**Comment by FransBouma** [comment]
I.e. there's a test with a sequence: https://github.com/FransBouma/Massive/blob/v2.0/tests/Oracle/ReadWriteTests.cs#L115 which succeeds. Please check what's different in your case.

**Comment by AlphaGeek509** [comment]
I'll certainly check right now.  I response to L115, I ran that test on my DB with my class.  The .Insert() method works exaxtly as desired.  It takes the sequence in the model definition and inserts the information correctly.

Once, I change .Insert() to .Save(), the .Save() method does not call the needed sequence subroutine for the insertion of a new record.  I hope that my late comment below sheds some light on what I'm attempting to say.  I really do appreciate your help and Massive.

**Comment by AlphaGeek509** [comment]
I'm working on an Oracle database did does not have the default SCOTT/TIGER instance created.  The joys of inheriting things in your job ;-)

I can recreate the issue by the following.  
-- Create table in Oracle

```
CREATE TABLE "PRINT_REV_CTRL" ("ID" NUMBER NOT NULL, "MFG_PART_ID" VARCHAR2(80BYTE));
```

-- Add constraint

```
ALTER TABLE "LT_DB"."PRINT_REV_CTRL" ADD CONSTRAINT "PRINT_REV_CTRL_ID_PK" PRIMARY KEY("ID");
```

--- Create Sequence

```
CREATE SEQUENCE  "LT_DB"."PRINT_REV_CTRL_SEQ"  MINVALUE 1100 MAXVALUE 99999999999999999999999999 INCREMENT BY 1 START WITH 1260 CACHE 20 NOORDER  NOCYCLE
```

--- Model

``` c#
public class PrintRevControl : DynamicModel
{
    public PrintRevControl() : this(includeSchema: true)
    {
    }

        public PrintRevControl(bool includeSchema)
            : base(TestConstants.ReadWriteTestConnectionStringName, includeSchema ? "LT_DB.PRINT_REV_CTRL" : "PRINT_REV_CTRL", "ID", string.Empty, includeSchema ? "LT_DB.PRINT_REV_CTRL_SEQ" : "PRINT_REV_CTRL_SEQ")
    {

    }
}
```

--- Unit Test

``` c#

[Test]
public void save_IsPrimaryKeyInserted()
{
     dynamic objPrc = new PrintRevControl();
     var inserted = objPrc.Save(new { MFG_PART_ID = "PART-NUMBER-12345" });
     int insertedPrcID = inserted.ID;

     Assert.IsTrue(insertedPrcID > 0);
}
```

--- Output of the error that I received running my test.
![screen shot 2016-01-15 at 2 08 05 pm](https://cloud.githubusercontent.com/assets/3721279/12366679/7de370c2-bb91-11e5-837e-308ca8699859.png)

**Comment by FransBouma** [comment]
That's indeed odd! I can't see a difference with the test I have....

**Comment by AlphaGeek509** [comment]
Frans,
I've submitted a Pull Request on the Oracle_CommandPropertyControl branch.  I believe that I've done things correctly, It's reproducing the sequence error on the SCOTT schema the same as I had on my LT_DB schema during the .Save() command.  If I did do something incorrectly during the Pull Request, please let me know, as it was my first ever pull request submission.  ;-)

**Comment by FransBouma** [comment]
NEVER change an existing test. Always add a test to illustrate your own issue :). Anyway, Save() is doing things differently than Insert() which is of course wrong indeed! So a new test for Save() has to be added, which will then fail, and a fix for that should then be added.

**Comment by AlphaGeek509** [comment]
I appreciate the guidance on testing.  I won't make that mistake in the future ;-)

**Comment by FransBouma** [comment]
Reproduced. Save() returns an int, not an object btw, so you have to use it differently: 

``` C#

        [Test]
        public void Save_SingleRow()
        {
            var depts = new Department();
            dynamic toSave = new {DNAME = "Massive Dep", LOC = "Beach"};
            var result = depts.Save(toSave);
            Assert.AreEqual(1, result);
            Assert.IsTrue(toSave.DEPTNO > 0);
            Assert.AreEqual(1, depts.Delete(toSave.DEPTNO));
        }
```

**Comment by FransBouma** [comment]
Issue should be fixed now. See https://github.com/FransBouma/Massive/blob/v2.0/tests/Oracle/ReadWriteTests.cs#L124 for usage :)

**Comment by AlphaGeek509** [comment]
Wanted to say thanks for this update. Pulled the latest code down last night and it was perfect!
