### ISSUE TITLE
Massive in ASP.NET 5

### ISSUE THREAD

**Issue by comfreakph** [FransBouma/Massive#258]
Hi, 

Is there a plan to support Massive in ASP.NET 5? because currently if you add this project in ASP.NET 5, it's not yet compatible

**Comment by FransBouma** [comment]
Connection string specification was added recently: https://github.com/FransBouma/Massive/pull/254

'not yet compatible' is too vague btw wat do you mean?

**Comment by FransBouma** [comment]
No info given -> closed
