### ISSUE TITLE
DNX plans

### ISSUE THREAD

**Issue by jasoncoding** [FransBouma/Massive#262]
Any plans to support DNX Core 5.0?  It's in RC so seems like the APIs are stable and won't be changing much.  I tried to drop the files in a project and got quite a few build errors.

**Comment by FransBouma** [comment]
what made you think RC means 'stable API' with respect to .NET core? ;) The APIs aren't stable at all. Just 4 days ago Microsoft checked in the first addition for DbDataReader.GetSchemaTable replacement. 

Once .NET Core contains all the required APIs (it currently doesn't) we'll think about porting. Besides, even the tooling isn't stable yet: 'DNX' for example will be renamed in the upcoming RC2 (which was delayed for a couple of reasons, one being things weren't done and therefore unstable).
