### ISSUE TITLE
Typo in SQLite project file

### ISSUE THREAD

**Issue by Barracuda72** [FransBouma/Massive#267]
Project file for SQLite, Massive.SQLite.csproj, references 

> Properties/SqliteAssemblyInfo.cs 

but it's wrong, real filename is

> Properties/SQLiteAssemblyInfo.cs

It doesn't matter on Windows, but on Linux (Mono) build fails, because it's two totally distinct filenames. Fix this please.

**Comment by FransBouma** [comment]
Fixed in #268
