### ISSUE TITLE
Reserved Word Conflict for SQL Server

### ISSUE THREAD

**Issue by aleblanc70** [FransBouma/Massive#269]
Do you have a workaround with massive when a column name = default ?
I try to find where in the source I can replace the columname with [default], no luck yet.
Best think is to rename the column but I try not too...

**Comment by FransBouma** [comment]
It doesn't do sanitizing on column names, so if you want to sanitize a column name in a query, you have to specify the query or the columns. E.g. when you're doing an `All()` call, you can specify the columns to fetch, which isn't ideal but it allows you to specify [default] instead, (but you have to specify the rest of the fields as well).
