### ISSUE TITLE
Potential Opportunity to Accelerate Paged DataBase Query in Massive.DynamicModel.BuildPagedResultAsync

### ISSUE THREAD

**Issue by Luo-Liang** [FransBouma/Massive#270]
Hey! First I really like Massive!

I took a look at the  Massive.DynamicModel.BuildPagedResultAsync method and realized there are two async queries to database:

````
result.TotalRecords = await ScalarAsync(queryPair.CountQuery, cancellationToken, args).ConfigureAwait(false);
result.Items = await QueryAsync(string.Format(queryPair.MainQuery, columns, TableName), cancellationToken, args).ConfigureAwait(false);
````
It seems like these two queries have no dependency, so it is possible to parallelize them:

````
var itemsTask = QueryAsync(string.Format(queryPair1.MainQuery, columns, TableName), cancellationToken, args).ConfigureAwait(false);
var totalRecTask = ScalarAsync(queryPair1.CountQuery, cancellationToken, args).ConfigureAwait(false);
result1.TotalRecords =  await totalRecTask;
result1.Items = await itemsTask;
````

I did a test on my machine with `AsyncReadTests.PagedAsync_OrderBySpecification_ColumnsSpecification` test, and I saw about 30% improvement in terms of latency. And if the sample database larger (AdventureWorks), the improvement can be even more on multicore processors.

I feel like this is a low hanging fruit for making Massive a little bit better :)

Thanks for your patience.

**Comment by FransBouma** [comment]
Async != concurrent programming, although it builds on top of the TPL. Async programming is solely meant to avoid busy waiting. So that things run in parallel when await is used is solely a coincidence, it also might not be happening, simply because how the tasks are scheduled is up to the executing context.

That said, I don't see how your code is any different than what's in the library other than that you switched the order. After all, the code in the library is exactly the same: task is created and awaited. :)

What could be the reason why you see a higher performance is that it might be the first query you ran on your database was 'cold', i.e. the database itself had to read the data from disk, then you changed the code and ran the updated query which was 'warm', as it didn't run into database latency as the resultset was already in-memory, cached, as the same SQL statement was executed.

**Comment by Luo-Liang** [comment]
Thanks for replying :)

Here is how it is different:
The order doesn't matter, the change is the use of await.  Since these two queries are independent, they should run in parallel (awaited only after both queries are issued, effectively overlapping computation), instead of in serial (awaited right after each query). Since SQL Server supports multiprocessor, running two queries without mutation can get up to 50% faster with multiprocessor. 

To illustrate the effect of parallelizing these two queries, please take a look at the average latency of running 10000 exact queries of PagedAsync_OrderBySpecification_ColumnsSpecification in the test folder:

<img width="371" alt="untitled" src="https://cloud.githubusercontent.com/assets/1490925/20498072/8d89ba10-afe0-11e6-9e95-d34e313443d2.png">

The speedup can get up to 50% in certain data set.

To recap the change:

````
//run in serial with QueryAsync
result.TotalRecords = **await** ScalarAsync(queryPair.CountQuery, cancellationToken, args).ConfigureAwait(false); 
//run in serial with ScalarAsync
result.Items = **await** QueryAsync(string.Format(queryPair.MainQuery, columns, TableName), cancellationToken, args).ConfigureAwait(false); 
````
to

````
 //implicit fork run in parallel with totalRecTask
var itemsTask = QueryAsync(string.Format(queryPair1.MainQuery, columns, TableName), cancellationToken, args).ConfigureAwait(false);
 //implicit fork run in parallel with itemsTask
var totalRecTask = ScalarAsync(queryPair1.CountQuery, cancellationToken, args).ConfigureAwait(false); 
//implicitly a WhenAll join.
result1.TotalRecords =  **await** totalRecTask;
result1.Items = **await** itemsTask;
````

Thanks!

**Comment by FransBouma** [comment]
Thanks for the info :) Interesting that there's a difference between first creating the task objects and then awaiting them vs. await the task and move on to the next. The reason I say that is that in the original code, the second await is in the continuation of the first await, but that's also the case in the newer code. I'm not saying you're lying, on the contrary, I'm just trying to understand why the two codeblocks are different as both await a task, the only difference in the original code being the second task is created in the continuation while in the newer code the task is created before the first await, but as that's just a task and not run at that point, I don't see how that leads to difference in latency. 

In the newer code, the second await also runs in the continuation of the first, not in parallel, meaning: if you specify 10 await *task* below each other you don't get 10 tasks running in parallel.

**Comment by FransBouma** [comment]
I figured it out :) 

```
var itemsTask = QueryAsync()..
```
returns immediately but does run. Both methods are started before the first await is issued. Learned something again which I had forgotten for some time!

Thanks for the heads up, @Luo-Liang! :)

**Comment by Luo-Liang** [comment]
Yes. You're exactly correct - now here is the difference: the issue time of these tasks are different. I think it's best explained using this example. Imagine our database calls are simply Task.Delay(5);

Now in the original code, we do:
await Task.Delay(5);
//5 seconds elapsed
await Task.Delay(5);
//another 5 seconds elapsed
//a total of 10 seconds elapsed.

In the new code, 
we have:
var task1 = Task.Delay(5);
var task2 = Task.Delay(5);
//no time has elapsed, we're just firing two tasks, they are not awaited for, so they are running in parallel,
await task1;
//5 seconds elapsed.
await task2;
//by the time task1 finished, task2 is almost finished.
//no second elapsed.
//a total of 5 seconds elapsed!

So back to the massive code, the same thing apply - in the original code, queries are **isssued** one after another - the second one is only issued when the first one is finished.
In the purposed new version, the two queries are **issued** in parallel, so SQL Server can execute them in parallel, just like our little delay toy example above, leveraging multiprocessor and whatever resource it takes.

Here are similar references :)

http://stackoverflow.com/questions/35374697/how-to-properly-make-asynchronous-parallel-database-calls

Thanks for your patience!

**Comment by Luo-Liang** [comment]
@FransBouma Ah great! Thanks for your patience!

**Comment by FransBouma** [comment]
Sorry for the long delay! 😊 Fixed now.
