### ISSUE TITLE
how to use Massive to sync the DataTable add/delete/update rows data into Database?

### ISSUE THREAD

**Issue by valinoment** [FransBouma/Massive#272]
I have transfered the List<dynamic> result data to DataTable, but how to use Massive to sync the DataTable add/delete/update rows data into Database ?

I`m trying to do the CRUD action with the database table.

**Comment by FransBouma** [comment]
Per row in your datatable you have to make calls to Massive to update records. The datatable should have its changes logged (so which rows are changed) and using that you can then call insert or update.
