### ISSUE TITLE
Mixed Unix/Windows line endings

### ISSUE THREAD

**Issue by mikebeaton** [FransBouma/Massive#282]
I noticed that in a few Massive files (e.g. `Massive.Shared.cs`) there are mixed Unix/Windows line endings. As far as I can see (this is from a quick look) most lines in most files have Windows endings, but a few edits here and there have used Unix endings instead.

I was going to look over this, make sure what the correct default was, change everything back to the default, and make a pull request.

Is this worth doing?

**Comment by FransBouma** [comment]
Likely a left over from Conery editing the code on a Mac. What I've rewritten (which is most code) has likely Windows line endings. 

It's ok, don't lose any sleep over it :) Modern editors can deal with it just fine, even arcane stuff like git! :)

**Comment by mikebeaton** [comment]
Okay, it does have the side effect that each time you open the file in Visual Studio it pops up a warning which you have to dismiss, at least on the default VS settings. (I wasn't looking for it, and certainly wouldn't have noticed otherwise.)

**Comment by mikebeaton** [comment]
(Also, when you respond to this dialog (each time you re-open the file) you have to choose the non-default option in VS, i.e. the one to leave the line endings alone, if you don't want to get a version of the file which reports loads of spurious white space changes against the original.)

**Comment by FransBouma** [comment]
Ah, I see I have this setting switched off (Environment -> documents -> Check inconsistent line endings on load). If you have this enabled it is indeed annoying. I switched if off rather quickly as the warning was annoying and sometimes you can't fix the line endings anyway (like tabs/spaces mixes). 

If it is annoying it should be fixed, so correcting them is indeed a good thing (I didn't know it was popping up a warning each time). When it's ported to .netstandard 2.0 and people on linux/mac will edit code too it will likely become a mess again, but that's life, I guess.

**Comment by mikebeaton** [comment]
To look into this, I ran this command:

`find . -type f -name '*.cs' -print0|xargs -0 unix2dos -1252`

for (I think) all text file types in the project (*.markdown, *.txt, *.csproj, *.sln, *.cs & *.config).

After doing this, `git status` reports only two files changed: `src/Massive.Shared.cs` and `tests/Oracle/ReadWriteTests.cs`.

A little more playing around in Visual Studio (enabling that warning, and playing with either converting to DOS or converting to Unix, and seeing what is reported as changed) reveals that these two files are almost entirely in Unix line endings, with a few Windows line endings here and there, where all the other files in the project have Windows line endings throughout.

So to make line endings consistent across the project and avoid that warning, I think all that is requried is that these two files need to be opened with that VS warning enabled, and converted to Windows line endings from the dialog.

This ends up looking like a bulky change in git, since almost every line in those two files reports a whitespace change (so I'm loath to upload it as a proposed pull, as it looks like I'm trying to propose huge changes when I'm not), but I think that's all that would be needed to make line endings across the project consistent, and avoid that warning.

**Comment by FransBouma** [comment]
Thanks for that :) I looked at the other files and indeed these are the only ones. Very strange, though that the oracle tests have these endings considering I created them from scratch! Oh well... :)
