### ISSUE TITLE
README.markdown Masssive not Massive (sorry if this is a stupid question!)

### ISSUE THREAD

**Issue by mikebeaton** [FransBouma/Massive#283]
Sorry, yet another one... and it may be a stupid question. In the project's main `README.markdown` file, where it says "**Masssive, a small, happy, dynamic MicroORM for .NET that will love you forever**"... is "**Masssive**" a typo for "**Massive**"? Or is it maybe an in-joke or something else intentional?! Even if it is a typo, just now is the first time I've noticed it myself, after looking at this file on and off for about a year. Hope this is of use.

**Comment by FransBouma** [comment]
LOL no that's not intended, but a clear typo. Never noticed it myself too!

**Comment by mikebeaton** [comment]
Created PR #286.
