### ISSUE TITLE
Developing for Massive - Oracle

### ISSUE THREAD

**Issue by mikebeaton** [FransBouma/Massive#288]
Massive supports SQL Server, Oracle, SQLite and PostgreSQL.

SQLite and PostgreSQL are both open source, so someone serious about developing Massive can get those. SQL Server and Oracle aren't.

Are the features of Massive compatible with free versions of these DBs? (In particular, the 'Express Edtion', which seems to be the name which both Oracle and SQL Server use for their free, 'entry-level' version). Is it reasonable to assume that if Massive works against Oracle/SQL Server Express Edition, it works against Oracle/SQL Server?

**Comment by FransBouma** [comment]
Yes.

**Comment by mikebeaton** [comment]
That's useful to know - might be worth mentioning in the new contributing section? Many thanks.

**Comment by FransBouma** [comment]
Added :)
