### ISSUE TITLE
PostgrSql test connection string

### ISSUE THREAD

**Issue by mikebeaton** [FransBouma/Massive#296]
On a standard windows install (latest BigSQL install of PostgreSql, lastest .msi install of Npgsql) the PostgrSql test connection string has the following problems:

`Protocol=3;` generates the error "Keyword not supported: protocol" during the test run. Removing it just works.

`Encoding=ASCII;` breaks accented character support in the Northwind database (test run error: "System.Text.DecoderFallbackException : Unable to translate bytes [C3] at index 22 from specified code page to Unicode." ). `Encoding=UNICODE;` also does not work. Removing it entirely works.

Obviously depending on whether these settings are neutral or required in other installs, can these just be removed?

**Comment by FransBouma** [comment]
Yes, these were needed for npgsql v2, and aren't needed for v3. What's strange is that the machine.config file on my testbox refers to npgsql v3.0.5 but only v2.2 is available. Some glitch somewhere. Anyway, it can be safely removed, as these two elements didn't anything anyway.

**Comment by FransBouma** [comment]
merged

**Comment by mikebeaton** [comment]
It took me quite a few hours of research into locale and encoding support in Postgres, plus a lot of reinitialising and recreating my Postgres cluster and Northwind database before I understood that I just needed to remove that Encoding setting and everything else worked with the default values. ;-/

Hopefully will save someone else that effort... at least until the underlying tools introduce breaking changes again!

**Comment by FransBouma** [comment]
Sorry, if had realized this I had removed it way before! My apologies for this trouble. here it worked fine but I used 3.0.5, not the latest build :/

**Comment by mikebeaton** [comment]
Not a problem - such things happen, of course! In general I am enjoying trying to contribute to Massive! Thank you. ;)

**Comment by mikebeaton** [comment]
(PS Assume there may be a difference between a Mono environment and a plain Windows environment, here? It looks like you're testing Postgres on Mono? Or maybe both Mono and plain Windows??)

**Comment by FransBouma** [comment]
No I don't use mono, only .NET on windows. Npgsql v2 required mono.security (it had a dependency on it) for its security internals, this dependency is gone in v3 so that's where the reference comes from :)
