### ISSUE TITLE
Misleading comment in PostgreSql limit code

### ISSUE THREAD

**Issue by mikebeaton** [FransBouma/Massive#306]
The `limit` code in [Massive.PostgrSql.cs](https://github.com/FransBouma/Massive/blob/v2.0/src/Massive.PostgreSQL.cs#L199-L200) has an incorrect comment:

````
// we have to wrap the query and then apply the rownum filter, as aggregates etc. otherwise aren't going to contain the right values, as they're then applied to the		
// limited set, not the complete set!
````

This comment does not apply to the PostgreSql `limit` code, only to the Oracle version from which this function must have been copied at some point.

The 6 lines (plus 2 lines of comment) of the PostgreSql limit code do exactly the same thing as the single line of limit code in Massive.Sqlite.cs, so I suggest removing the misleading comment, and just using the simpler Sqlite version of the same code instead.

**Comment by FransBouma** [comment]
Merged
