### ISSUE TITLE
.gitattributes is incorrect

### ISSUE THREAD

**Issue by mikebeaton** [FransBouma/Massive#309]
Frans,

I was still getting whitespace problems and looked into it some more.

The `.gitattributes` file is wrong, it reads `text=auto` but should read `* text=auto`. This will only be noticed by someone who has `git config --global core.autocrlf` set to `false`.

I have tested this change and it makes the intended difference: cloning Massive from the main repository onto my Windows machine (with the above global config setting, which I want for other reasons) I get various files with Unix line endings and hence a sea of green and red if I start editing, but cloning from a version with the revised `.gitattributes` file everything works properly.

Mike

**Comment by FransBouma** [comment]
Merged!
