### ISSUE TITLE
Inconsistent line endings (still!)

### ISSUE THREAD

**Issue by mikebeaton** [FransBouma/Massive#313]
Dear Frans,

Sorry about this, more line endings stuff.

Because `.gitattributes` was wrong a few of the files in the project (unfortunately including `Massive.Shared.cs`) are inconsistently stored in Github. Most files are correctly stored with UNIX LF and a UTF-8 byte order mark (as you would expect if you commit a standard Windows CRLF+BOM file, using Git setting `text=auto` &/or `core.autocrlf=true`).

But for these files, this isn't true:

        modified:   LICENSE.txt
        modified:   README.markdown
        modified:   src/Massive.MySql.cs
        modified:   src/Massive.Oracle.cs
        modified:   src/Massive.PostgreSQL.cs
        modified:   src/Massive.Shared.cs
        modified:   src/Massive.SqlServer.cs
        modified:   src/Massive.Sqlite.cs
        modified:   tests/Oracle/ReadWriteTests.cs
        modified:   tests/SqlServer/App.config

(I auto-generated this changeset by using `dos2unix -m` on every file, starting with a repository clone made from just before the `.gitattributes` fix, and using setting `git config --global core.autocrlf false`. These are the only files which then show as changed.)

8 of these 10 files are just lacking the byte order mark - a trivial and unimportant inconsistency.

But two files, `Massive.Shared.cs` and `Oracle/ReadWriteTest.cs` were stored with Windows CRLF line endings in the repository. This unfortunately means that with the new, correct, `.gitattributes` file, then any commits to either of these files results in a sea of green and red on Github (since with the new, correct settings they are written back with Unix LF instead, after any changes).

The correct solution is a one off commit to correct all the above. I have made the commit and checked this, I can now edit ANY file (including the two with the serious line-ending problems) and only the changed lines show in the commit.

**Comment by FransBouma** [comment]
Done.

**Comment by mikebeaton** [comment]
(Useful commands in #282)
