### ISSUE TITLE
Any solution for massive and .net core confilict?

### ISSUE THREAD

**Issue by mirshahreza** [FransBouma/Massive#320]
Hi, 
I used the massive many times and I track the discussion you done with .net core team.
I have to migrate to .net core but the problem is I can not use the massive with .net core profile.

I need some features that is not in another solution I think like this examples 👍 

var result = tbl.Paged(where: "UnitPrice > 20", currentPage:2, pageSize: 20);

or 

        DynamicModel db = new DynamicModel("ConnectionStrings:DefaultConnection", "T1", "Id");
        var inserted = db.Insert(new { Name = DateTime.Now.ToString() });

it is wonderful for me because it can works dynamically with objects , means I do not have to make and map strongly typed objects.

so at least this tow features force me for using your library.

Now I have tow solution :

1- Choosing another micro orm with this features : I don't know such micro orm . Is there any micro orm with this important features?

2- Using full .net framework : By this solution I can not compile my project for other platforms.

Any idea to solving this problem?

By the way I test the .net core 2 and it doesn't work .

Thanks
Mohsen

**Comment by FransBouma** [comment]
what's the problem with .net core? If it's datatable etc. then yes that's  a known issue, but .net core 2.0 should fix that. I'll port Massive to .net standard 2.0 (if it doesn't already compile against that, haven't checked) when that's released.

**Comment by mirshahreza** [comment]
Ok, 
Thus I must to wait for resolving the issue by .net core team and I can continue with full .net profile.

Thanks

**Comment by FransBouma** [comment]
Still would be interesting to know what went wrong :)
