### ISSUE TITLE
SQL syntax error when accessing a SQLite table's Schema property

### ISSUE THREAD

**Issue by jim-wilson-kt** [FransBouma/Massive#322]
A few hours of research just leaves me to _speculate_ that SQLite PRAGMA queries may not support parameters. The following modified code from Massive.Sqlite.cs explains what doesn't work and what does:

```C#
protected virtual string TableWithoutSchemaQuery
{
    // Original getter, which results in a SQL syntax error.
    get { return "PRAGMA table_info(@0)"; }

    // Also results in a SQL syntax error
    get { return "PRAGMA table_info=@0"; }

    // Works
    get { return $"PRAGMA table_info='{this.TableName}'"; }

    // Also works
    get { return $"PRAGMA table_info('{this.TableName}')"; }
}
```

Of course you need to comment out (or delete) the first two and one of the last two getters for the code above to work.

**Comment by FransBouma** [comment]
Is this code ran during the sqlite tests? As the tests succeed, so it leads me to the conclusion it might work ;) but haven't checked with ncover whether these lines are covered with tests tbh...

**Comment by jim-wilson-kt** [comment]
I don't think so, but I should download all of the source and run the tests. There is a test for SQL Server called SchemaMetaDataRetrieval(), but there is not a corresponding one for SQLite. Furthermore, there is no SQLite test that gets a table's Schema property. I will investigate more and check out the code contribution requirements, if applicable. Note that my work-around in the original post doesn't pass the code-smell test in that it injects variable content into the SQL statement and then later a parameter is added to the DbCommand object that is never used. However, the SQL-injection risk seems minimal (perhaps impossible) and the unused parameter doesn't hurt anything.

**Comment by FransBouma** [comment]
This looks like a bug, albeit an edge case, as sqlite doesn't support schemas like oracle/sqlserver etc. do, so the table name with or without schema info is the same: just the table name. 

As PRAGMA doesn't support parameters, there's no other option but to embed the table name. It's indeed not that great wrt to sql injection but as you say,  in practice this won't exist as the name is specified in the class constructor, so only if the developer uses a dynamic model class which is instantiated with a name obtained from user input this might go wrong. 

Will fix.

**Comment by FransBouma** [comment]
Fixed
